# Generated by Django 3.2.25 on 2025-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'ordering': ['day_of_week', 'meal_type'], 'verbose_name_plural': 'Food Menus'},
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
    ]
