# Generated by Django 3.2.25 on 2025-10-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0002_auto_20251001_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='day_of_week',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=10),
        ),
    ]
