# Generated by Django 3.2.25 on 2025-10-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0004_auto_20251003_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mess_app.user'),
            preserve_default=False,
        ),
    ]
