# Generated by Django 6.0.1 on 2026-01-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0007_mealrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
